export const domains = [
  "angularwork.com",
  "eastevent.co",
  "easteventco.com",
  "firecro.com",
  "formamp.com",
  "leadspree.co",
  "leadspree.io",
  "leadtrics.com",
  "mywoodinvillewedding.com",
  "nwglamp.com",
  "podtasks.com",
  "quizspree.io",
  "staystream.com",
  "tubeamp.io",
  "uplighting.co",
  "uplightingco.com",
  "vidtasks.com",
  "woodinvilleeventcenter.com",
  "woodinvilleeventscenter.com",
  "woodinvillephotoco.com",
  "zeroload.io",
  "staychain.com",
];

export default domains;
